//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutrinetSync.ModeloSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public paciente()
        {
            this.historias = new HashSet<historias>();
        }
    
        public long pacienteid { get; set; }
        public string nombres { get; set; }
        public string apellidop { get; set; }
        public string apellidom { get; set; }
        public System.DateTime fechanac { get; set; }
        public string sexo { get; set; }
        public long estadocivil { get; set; }
        public string telefonos { get; set; }
        public string correo { get; set; }
        public string referente { get; set; }
        public string calle { get; set; }
        public string numext { get; set; }
        public string numint { get; set; }
        public string colonia { get; set; }
        public string localidad { get; set; }
        public string municipio { get; set; }
        public string ciudad { get; set; }
        public string ciudadorigen { get; set; }
        public string estado { get; set; }
        public string pais { get; set; }
        public string nombrepadre { get; set; }
        public string nombremadre { get; set; }
        public System.DateTime ultimaconsulta { get; set; }
        public decimal peso { get; set; }
        public decimal talla { get; set; }
        public string nivelactividad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historias> historias { get; set; }
    }
}
