//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutrinetSync.ModeloSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class historias
    {
        public long historiaid { get; set; }
        public Nullable<long> pacienteid { get; set; }
        public string historia { get; set; }
    
        public virtual paciente paciente { get; set; }
    }
}
